package kluzzio.roa.api.util;

import net.minecraft.entity.Entity;
import net.minecraft.entity.EntityType;
import net.minecraft.entity.LivingEntity;

import java.util.List;

import static net.minecraft.entity.EntityType.*;

public class EntityHelper {

    public static final List<EntityType<? extends Entity>> LIVING_ENTITY_TYPE_LIST = List.of(AXOLOTL, BAT, BEE, BLAZE,
            CAT, CAVE_SPIDER, CHICKEN, COD, COW, CREEPER, DOLPHIN, DONKEY, DROWNED, ELDER_GUARDIAN, ENDER_DRAGON,
            ENDERMAN, ENDERMITE, EVOKER, FOX, GHAST, GLOW_SQUID, GOAT, GUARDIAN, HOGLIN, HORSE, HUSK, IRON_GOLEM, LLAMA,
            MAGMA_CUBE, MULE, MOOSHROOM, OCELOT, PANDA, PARROT, PHANTOM, PIG, PIGLIN, PIGLIN_BRUTE, PILLAGER, POLAR_BEAR,
            PUFFERFISH, RABBIT, RAVAGER, SALMON, SHEEP, SHULKER, SILVERFISH, SKELETON, SKELETON_HORSE, SLIME, SNOW_GOLEM,
            SPIDER, SQUID, STRAY, STRIDER, TRADER_LLAMA, TROPICAL_FISH, TURTLE, VEX, VILLAGER, VINDICATOR,
            WANDERING_TRADER, WITCH, WITHER, WITHER_SKELETON, WOLF, ZOGLIN, ZOMBIE, ZOMBIE_HORSE, ZOMBIE_VILLAGER,
            ZOMBIFIED_PIGLIN);

    public static final List<EntityType<? extends Entity>> POS_ENTITY_TYPE_LIST = List.of(BAT, BEE, BLAZE, CAVE_SPIDER,
            CHICKEN, COD, COW, CREEPER, DONKEY, DROWNED, ELDER_GUARDIAN, ENDER_DRAGON, ENDERMITE, EVOKER, GHAST,
            GLOW_SQUID, GOAT, GUARDIAN, HOGLIN, HORSE, HUSK, IRON_GOLEM, LLAMA, MAGMA_CUBE, MULE, MOOSHROOM, OCELOT,
            PANDA, PARROT, PHANTOM, PIG, PIGLIN, PIGLIN_BRUTE, PILLAGER, POLAR_BEAR, PUFFERFISH, RABBIT, RAVAGER, SALMON,
            SHEEP, SHULKER, SILVERFISH, SKELETON, SKELETON_HORSE, SLIME, SNOW_GOLEM, SPIDER, SQUID, STRAY, STRIDER,
            TRADER_LLAMA, TROPICAL_FISH, TURTLE, VEX, VILLAGER, VINDICATOR, WANDERING_TRADER, WITCH, WITHER,
            WITHER_SKELETON, ZOGLIN, ZOMBIE, ZOMBIE_HORSE, ZOMBIE_VILLAGER, ZOMBIFIED_PIGLIN);

    public static final List<EntityType<? extends Entity>> NEG_ENTITY_TYPE_LIST = List.of(AXOLOTL, CAT, DOLPHIN,
            ENDERMAN, FOX, WOLF);

    public static boolean validEntityType(LivingEntity livingEntity) {
        return LIVING_ENTITY_TYPE_LIST.contains(livingEntity.getType());
    }
}